upstream backend {
    server backend:8000;
}

server {
    listen 80;
    listen [::]:80;
    
    error_log /var/log/nginx/app.error.log;
    access_log /var/log/nginx/app.access.log;
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript application/xml image/svg+xml;


location / {
    return 200 "nginx is running";

}

location /api/ {
    proxy_pass http://backend/;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr ;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /health/ready {
    proxy_pass http://backend/health/ready;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
}