services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    restart: unless-stopped
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    container_name: backend
    environment:
      APP_ENV: production
      SERVICE_NAME: observable-shop
      LOG_LEVEL: INFO
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - app-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-network
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network
    restart: unless-stopped
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - app-network
    restart: unless-stopped
  postgres-zabbix:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    volumes:
      - zabbix-postgres-data:/var/lib/postresql/data
    networks:
      - app-network
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    environment:
      DB_SERVER_HOST: postgres-zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - postgres-zabbix
    expose:
      - "10051"
    networks:
      - app-network
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: postgres-zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PHP_TZ: Asia/Yekaterinburg
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    networks:
      - app-network
    restart: unless-stopped

  zabbix-agent:
    image: imageNamezabbix/zabbix-agent2:alpine-7.0-latest
    environment:
      ZBX_HOSTNAME: observable-shop-host
      ZBX_SERVER_HOST: zabbix-server
    networks:
      - app-network
    restart: unless-stopped

volumes:
  grafana-data:
  elasticsearch-data:
  zabbix-postgres-data:
networks:
  app-network:
    driver: bridge
