apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

    jsonData:
      httpMethod: POST
      timeInterval: 15s
      queryTimeout: 60s
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 2.54.0
      cacheLevel: high
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
